name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Requirements
        run: pip install --trusted-host pypi.python.org -r requirements.txt

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Docker Login
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > key.json
          cat key.json | docker login -u _json_key --password-stdin '${{ vars.GOOGLE_ARTIFACT }}'

      - name: Build & Push Image
        run: |
          docker build -t ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GOOGLE_REPONAME }}/${{ vars.GOOGLE_MYAPP }}:latest .
          docker push ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GOOGLE_REPONAME }}/${{ vars.GOOGLE_MYAPP }}:latest

  Deploy-Production:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Auth GCP
        uses: "google-github-actions/auth@v1" # https://github.com/google-github-actions/auth
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Cloud Run Deploy - Production
        id: prod-deploy
        uses: "google-github-actions/deploy-cloudrun@v1" # https://github.com/marketplace/actions/deploy-to-cloud-run
        with:
          service: ${{ vars.GOOGLE_MYAPP }}-prod
          image: ${{ vars.GOOGLE_ARTIFACT }}/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GOOGLE_REPONAME }}/${{ vars.GOOGLE_MYAPP }}:latest
          flags: "--set-env-vars CLOUD_SQL_USERNAME=playlist,CLOUD_SQL_PASSWORD=abc12345678#*,CLOUD_SQL_DATABASE_NAME=playlist,DB_LOCAL_HOST=34.138.50.5 --allow-unauthenticated"

      - name: Test Prod
        run: 'curl "${{ steps.prod-deploy.outputs.url }}"'
